//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pz3_Mebel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mebel
    {
        public int IdMebel { get; set; }
        public string Name { get; set; }
        public string Material { get; set; }
        public int IdTipeMebely { get; set; }
        public string Style { get; set; }
        public int Kolichestvo { get; set; }
    
        public virtual TipeMebel TipeMebel { get; set; }
    }
}
